### PR TITLE
From switch.broadlink to script

### PR DESCRIPTION
**Pull request by unclehook**

### CODE REVIEW

**Comment by keitetran** [comment]
Nice !!! Thank for help.

**Comment by keitetran** [comment]
:( why u need create a script on HASS ? 
On my code can call a service on hass with IP address input. 
``` 
sendBroadlinkLearnCmd(_ip) {
    store.state.socket.send(JSON.stringify({
      id: store.state.socketId++,
      type: "call_service",
      domain: "broadlink",
      service: "learn",
      service_data: {
        host: _ip
      }
    }));
  },
```

**Comment by keitetran** [comment]
Thank you verry much, but we dont need edit hass config file. I will drop this PR. Sorry :(

**Comment by unclehook** [comment]
Hi @keitetran,
i wrote "why" in the README.md: "It's a workaroud, please understand, I have too low knowledge of nodejs to made a more elegant solution.";

My intent was to primarly made the tools return to work in less time possibile, then study code and language to find a better solution.

Fortunately, you solved it before I started studying.

**This for say: don't worry about dropping my code ;)**

**Thank you for the tool**


--
_**WORKAROUND**: essentially a temporary measure to reduce or eliminate the impact of an Incident or a Problem. It can be used to fix the issue the user is facing until a permanent solution can be implemented._

**Comment by unclehook** [comment]
P. S .: let me know when you read this comment, so I cancel my reporitory. I fear that if I delete it now the PR and his comments will also disappear.

**Pull request closed without merging**
